### PR TITLE
Create passwordgenerator.py

### PR DESCRIPTION
**Pull request by Bobliuuu**
Created a strong password generator!

### CODE REVIEW

**Comment by Bobliuuu** [comment]
Hey @whitehathackers-klef! Could you please take a look at the PR? 😃

**Comment by whitehathackers-klef** [comment]
Good work Bobliuuu, you did successfully created a password generator but you still did not meet all the requirements of the issue please read it carefully again.

**Comment by Bobliuuu** [comment]
> A password generator is a tool that automatically generates a password based on guidelines that you set to create strong and unpredictable passwords for each of your accounts to boost online security.

Do you mean this (from #4)? I read this, and I believe that I followed your instructions. After you input guidelines (the length of the password), the program generates a strong password based on these guidelines. 
If you would like me to change it, please suggest specific changes, but I think I did follow the issue when creating my program.

**Comment by whitehathackers-klef** [comment]
You have done only the first part of the question Bobliuuu, we still require you to store the passwords generated in a database like MySQL, MongoDB, etc., then you must also include a feature in your code that checks user input password.

**Comment by Bobliuuu** [comment]
Hi @whitehathackers-klef thank you for the explicit instructions! I will also do that part. 
The "second part of the question" is not written anywhere, so I could not have known that it needed to be implemented beforehand. Next time, please put all your instructions in the relevant issue. Thanks! 
Also, what do you mean "check user input password"? I'm implementing a password generator, checking user input passwords is not part of what a password generator does.

**Pull request merged**
